INSERT INTO effects
VALUES
	(1,'Anti-Gravity'),
	(2,'Athletic'),
	(3,'Balding'),
	(4,'Bright-Eyed'),
	(5,'Calming'),
	(6,'Calorie-Dense'),
	(7,'Cyclopean'),
	(8,'Disorienting'),
	(9,'Electrifying'),
	(10,'Energizing'),
	(11,'Euphoric'),
	(12,'Explosive'),
	(13,'Focused'),
	(14,'Foggy'),
	(15,'Gingeritis'),
	(16,'Glowing'),
	(17,'Jennerising'),
	(18,'Laxative'),
	(19,'Lethal'),
	(20,'Long Faced'),
	(21,'Munchies'),
	(22,'Paranoia'),
	(23,'Refreshing'),
	(24,'Schizophrenic'),
	(25,'Sedating'),
	(26,'Seizure-Inducing'),
	(27,'Shrinking'),
	(28,'Slippery'),
	(29,'Smelly'),
	(30,'Sneaky'),
	(31,'Spicy'),
	(32,'Thought-Provoking'),
	(33,'Toxic'),
	(34,'Tropic Thunder'),
	(35,'Zombifying')

